### ISSUE TITLE
Failed to resolve: com.github.maximillianleonov:blurimage:1.0.0

### ISSUE THREAD

**Issue by ghost** [MaximillianLeonov/BlurImage#8]
I trying to use this library but android studio show this error I added jitpack.io in settings gradle but there is still same error

**Comment by AfigAliyev** [comment]
Hi. Thanks for submitting this. The issue was the missing `v` prefix for the version. I have updated the README.

- `build.gradle` / `build.gradle.kts`

**Groovy:**

```gradle
implementation "com.github.maximillianleonov:blurimage:v1.0.0"
```

**Kotlin DSL:**

```kotlin
implementation("com.github.maximillianleonov:blurimage:v1.0.0")
```

**Comment by ynsemreyildirim** [comment]
unfortunately it didn't work, still have the same problem. Could the problem be caused by something else?
![ss](https://user-images.githubusercontent.com/105103466/213161616-6babd540-f21b-44e6-ba09-4a8683472127.png)

**Comment by ghost** [comment]
Thank you so much for your help. It is done.

**Comment by AfigAliyev** [comment]
You are welcome :)
